#!/bin/sh

# Fix java applications misbehaving
export _JAVA_AWT_WM_NONREPARENTING=1

# Start sxhkd
pgrep -x sxhkd >/dev/null || sxhkd &

# Enable window swallowing
pgrep bspswallow || bspswallow &

# Start picom
pgrep picom || picom -b

# Start polybar
~/.config/polybar/launch.sh

# Start polkit-gnome
pgrep -af polkit-gnome-au || /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Start thunar daemon
pgrep thunar || thunar --daemon &

# Fix incorrect cursor on desktop
xsetroot -cursor_name left_ptr

# Set up monitors
if [[ $(xrandr -q | grep "HDMI-1-0 connected") ]]; then
  xrandr --output eDP-1 --primary --auto --pos 1920x0 --rotate normal \
    --output HDMI-1-0 --auto --pos 0x0 --rotate normal

  # Give each monitor 5 workspaces
  bspc wm -O HDMI-1-0 eDP-1
  bspc monitor HDMI-1-0 -d $(seq -s " " 1 5)
  bspc monitor eDP-1 -d $(seq -s " " 6 10)
else
  xrandr --output eDP-1 --primary --auto --pos 0x0 --rotate normal

  # Give main monitor the workspace
  bspc monitor eDP-1 $(seq -s " " 1 10)
fi

# Set the wallpaper
feh --no-fehbg --bg-fill --randomize "$HOME"/git/wallpapers/* &

bspc config border_width 2
bspc config window_gap 3

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

# Fix the polybar gap issue
bspc config ignore_ewmh_struts true

# Fix windows covering polybar on the main monitor
bspc config -m eDP-1 top_padding 37

# Set picture in picture windows to float
bspc rule -a '*:*:Picture-in-Picture' state=floating

# Make Gimp windows float
bspc rule -a Gimp state=floating follow=on

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

# Ensure clipmenu has the DISPLAY environment variable
systemctl --user import-environment DISPLAY
