#!/bin/zsh
# Navigation
alias ..='cd ..'
alias ...='cd ../..'
alias .2='cd ../..'
alias .3='cd ../../..'
alias .4='cd ../../../..'
alias .5='cd ../../../../..'

# ls flag variations
alias ls='eza -Mal --color always --group-directories-first --git --color-scale size --no-quotes'
alias la='eza -Ma --color always --group-directories-first --color-scale size --no-quotes'
alias ll='eza -Ml --color always --group-directories-first --git --color-scale size --no-quotes'
alias lt='eza -MaT --color always --group-directories-first --ignore-glob ".git" --color-scale size --no-quotes'
alias l.='eza -a | grep "^\."'

# Output coloring
alias grep='grep --color=auto'
alias diff='diff --color=auto'
alias ip='ip -color=auto'

# Sets output as human readable
alias df='df -h'
alias du='du -h'
alias free='free -h'

# Overwrite confirmations
alias cp='cp -iv'
alias mv='mv -iv'
alias rm='rm -i'

# Termbin
## REMEMBER TO PIPE OUTPUT
alias tb='nc termbin.com 9999'

# Shortcuts
alias se='sudoedit'
alias wget='wget --continue --hsts-file="$XDG_DATA_HOME"/wget-hsts'
alias nvidia-settings='nvidia-settings --config="$XDG_CONFIG_HOME"/nvidia/settings'

## Internet connection
alias check='ping -c 4 archlinux.org'
alias myip='curl ip.me'
# alias speed='speedtest --single --secure'

# Pacman
alias cleanup='sudo pacman -Rns $(pacman -Qtdq)'

## yt-dlp shortcuts
alias ytdl-audio='yt-dlp --config-locations ~/.config/yt-dlp/audio'
alias ytdl-music='yt-dlp --config-locations ~/.config/yt-dlp/music'
alias ytdl-video='yt-dlp --config-locations ~/.config/yt-dlp/video'
alias ytdl-video-cc='yt-dlp --config-locations ~/.config/yt-dlp/video-cc'
alias ytdl-thumbnail='yt-dlp --list-thumbnail'

# Find a video with fzf and play with mpv
mpvf() { fd "mp4$|mkv$" --type=f --color=never ~/Videos/ | fzf --scheme=path | sed 's/^/"/;s/$/"/' | xargs -rI % mpv %; }

# kitty terminal specific aliases
# icat alias
alias icat='kitty +kitten icat'

# kitty ssh alias
alias ssh="kitty +kitten ssh"

## Pihole shortcuts
alias pihole='kitten ssh amaterasu'
alias pi-update='kitten ssh -t amaterasu "sudo apt update && sudo apt upgrade -y"'
alias pi-gravity='kitten ssh -t amaterasu "sudo pihole -g"'
alias pi-shutdown='kitten ssh -t amaterasu "sudo systemctl poweroff"'
alias pi-reboot='kitten ssh -t amaterasu "sudo systemctl reboot"'

## Terminal
# HACK: For some reason, clear doesn't work properly with xterm-kitty when output exceeds number of rows
# Tricking clear into thinking we're using xterm-256color seems to fix things
alias cl='TERM=xterm-256color clear'
alias clear='TERM=xterm-256color clear'

# Fix adb
alias adb='HOME=$XDG_DATA_HOME/android adb'

# Abbreviations
if type abbr >/dev/null; then
  abbr p='pacman'
  abbr pa='paru'
  abbr sp='sudo pacman'
  abbr sps='sudo pacman -S'
  abbr pqi='pacman -Qi'
  abbr psi='pacman -Si'
  abbr g='git'
  abbr ga='git annex'
  abbr v='vim'
  abbr ch='chezmoi'
  abbr cha='chezmoi add'
  abbr chd='chezmoi diff'
  abbr che='chezmoi edit'
  abbr chap='chezmoi apply'
  abbr chg='chezmoi git'
  abbr chc='chezmoi cd'
  abbr chdx='chezmoi diff -x'
  abbr pagp="paru -Gp"
fi

# Fun
## Terminal rickroll
# alias rr='curl -sL https://raw.githubusercontent.com/keroserene/rickrollrc/master/roll.sh | bash'
## Dancing parrot
# alias parrot='curl parrot.live'
## Starwars
# alias starwars='curl https://asciitv.fr'
## Run, Forest, run!
# alias forest='curl ascii.live/forrest'
## Minesweeper (password: play)
# alias minesweeper='ssh play@anonymine-demo.oskog97.com -p 2222'

# Power
alias rbn='reboot'
alias sdn='shutdown now'
