#!/bin/sh
# NOTE: Do not move the xdg environment variables
# You will not be able to login to the desktop environment, since $ICEAUTHORITY depends on these variables
# Don't be stupid, don't move them
export XDG_CACHE_HOME=$HOME/.cache
export XDG_CONFIG_HOME=$HOME/.config
export XDG_DATA_HOME=$HOME/.local/share
export XDG_STATE_HOME=$HOME/.local/state

export CUDA_CACHE_PATH="$XDG_CACHE_HOME"/nv
export GNUPGHOME="$XDG_DATA_HOME"/gnupg
export ICEAUTHORITY="$XDG_CACHE_HOME"/ICEauthority
export WINEPREFIX="$XDG_DATA_HOME"/wine
export DVDCSS_CACHE="$XDG_DATA_HOME"/dvdcss
# export ZDOTDIR="$XDG_CONFIG_HOME"/zsh
export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="$XDG_CONFIG_HOME"/java
export SXHKD_SHELL="/bin/sh"
export GTK2_RC_FILES="$XDG_CONFIG_HOME"/gtk-2.0/gtkrc
export SWALLOW_APPLICATIONS="nsxiv|zathura|mpv"
export SWALLOW_TERMINALS="kitty"

# Append to the path
typeset -U path PATH
path=(~/.local/bin $path)
export PATH
