#!/bin/zsh

export XDG_CACHE_HOME="$HOME"/.cache
export XDG_CONFIG_HOME="$HOME"/.config
export XDG_DATA_HOME="$HOME"/.local/share
export XDG_STATE_HOME="$HOME"/.local/state

# export CUDA_CACHE_PATH="$XDG_CACHE_HOME"/nv
export GNUPGHOME="$XDG_DATA_HOME"/gnupg
export ICEAUTHORITY="$XDG_CACHE_HOME"/ICEauthority
export WINEPREFIX="$XDG_DATA_HOME"/wine
export DVDCSS_CACHE="$XDG_DATA_HOME"/dvdcss
# export ZDOTDIR="$XDG_CONFIG_HOME"/zsh
export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="$XDG_CONFIG_HOME"/java
export GTK2_RC_FILES="$XDG_CONFIG_HOME"/gtk-2.0/gtkrc

# Append to the path
typeset -U path PATH
path=(~/.local/bin $path)
export PATH

# Editor config
export EDITOR="$(command -v nvim)"
export VISUAL="$EDITOR"
export DIFFPROG="$EDITOR -d"

# Exports
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME"/npm/npmrc
export NPM_CONFIG_CACHE="$XDG_CACHE_HOME"/npm
export NPM_CONFIG_INIT_MODULE="$XDG_CONFIG_HOME"/npm/config/npm-init.js
export PYTHON_HISTORY="$XDG_STATE_HOME"/python_history
export NODE_REPL_HISTORY="$XDG_STATE_HOME"/node_repl_history
export GPG_TTY=$(tty)
export LESSHISTFILE="$XDG_STATE_HOME"/less/history
export PARALLEL_HOME="$XDG_CONFIG_HOME"/parallel
export ANDROID_USER_HOME="$XDG_DATA_HOME"/android

# History related exports
# export HISTORY_IGNORE="(ls|la|ll|cd|pwd|exit|sdn|rbn|history|cd -|cd ..|..|...|cl|clear|z)"
export HISTCONTROL=ignoredups:erasedups
export HISTFILE="$XDG_STATE_HOME"/zsh/history
export HISTSIZE=10000
export SAVEHIST="$HISTSIZE"
export HISTDUP=erase

# Use bat as manpager
export MANPAGER="sh -c 'col -bx | bat -l man -p'"

# Fix formatting for manpager
export MANROFFOPT="-c"

# Less options
export LESS="-R -i -F"

# golang xdg dirs
export GOPATH="$XDG_DATA_HOME"/go
