#!/bin/zsh

# Editor config
export EDITOR=$(which nvim)
export VISUAL=$EDITOR
export DIFFPROG="$EDITOR -d"

# Exports
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME"/npm/npmrc
export NPM_CONFIG_CACHE="$XDG_CACHE_HOME"/npm
export NPM_CONFIG_INIT_MODULE="$XDG_CONFIG_HOME"/npm/config/npm-init.js
export PYTHON_HISTORY="$XDG_STATE_HOME"/python_history
export NODE_REPL_HISTORY="$XDG_STATE_HOME"/node_repl_history
export GPG_TTY=$(tty)
export LESSHISTFILE="$XDG_STATE_HOME"/less/history
export PARALLEL_HOME="$XDG_CONFIG_HOME"/parallel
export ANDROID_USER_HOME="$XDG_DATA_HOME"/android

# History related exports
# export HISTORY_IGNORE="(ls|la|ll|cd|pwd|exit|sdn|rbn|history|cd -|cd ..|..|...|cl|clear|z)"
export HISTCONTROL=ignoredups:erasedups
export HISTFILE="$XDG_STATE_HOME"/zsh/history
export HISTSIZE=10000
export SAVEHIST=$HISTSIZE
export HISTDUP=erase

# Use bat as manpager
export MANPAGER="sh -c 'col -bx | bat -l man -p'"

# Fix formatting for manpager
export MANROFFOPT="-c"

# Keep coloring with piped input into less
export LESS="-R"
