# Use custom format
format = """
$username$directory$lua$c$python$fill$git_metrics$git_status$git_branch$git_state$git_commit
$character
"""

# Disables blank line between shell prompts
add_newline = false

# Use spaces for fill module
[fill]
symbol = " "

# Replace the "❯" symbol in the prompt with ""
[character]
success_symbol = "[](bold #9ece6a)"
error_symbol = "[](bold #db4b4b)"
vimcmd_symbol = "[](bold #9ece6a)"
vimcmd_visual_symbol = "[](bold #e0af68)"
vimcmd_replace_symbol = "[](bold #9d7cd8)"
vimcmd_replace_one_symbol = "[](bold #9d7cd8)"

# Username style options
[username]
format = '\[[$user]($style)\] '
style_root = "bold #db4b4b"

# Directory options
[directory]
format = "[$path]($style) [$read_only]($read_only_style)"
truncation_length = 8
truncation_symbol = "../"
truncate_to_repo = false
read_only = "󰌾"
style = "bold #769ff0"

# Git branch
[git_branch]
format = '\[[$symbol$branch](bold #769ff0)\]($style) '
symbol = " "
style = "bold #394260"

# Git commit
[git_commit]
only_detached = false
format = '[\($hash$tag\)]($style)'
style = "bold #9ece6a"

# Git status
[git_status]
format = '([\[$all_status$ahead_behind\]]($style)) '
style = "bold #394260"

# Git metrics
[git_metrics]
disabled = false
# only_nonzero_diffs = false

[c]
symbol = " "
format = '\[[$symbol($version(-$name))]($style)\] '
style = "bold #9ece6a"
detect_extensions = ["c", "h", "cc", "cpp", "hh", "hpp"]

[lua]
symbol = " "
format = '\[[$symbol($version)]($style)\] '
style = "bold #7aa2f7"

[python]
symbol = " "
format = '\[[${symbol}${pyenv_prefix}(${version}) (\($virtualenv\))]($style)\]'
style = "bold #e0af68"
