# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Use custom format
format = """
$username$directory$fill$lua$c$python$nodejs$git_metrics$git_status$git_branch$git_state$git_commit
$character
"""

# Disables blank line between shell prompts
add_newline = false

# Use spaces for fill module
[fill]
symbol = " "

# Replace the "❯" symbol in the prompt with ""
[character]
success_symbol = "[](bold green)"
error_symbol = "[](bold red)"
vimcmd_symbol = "[](bold green)"
vimcmd_visual_symbol = "[](bold yellow)"
vimcmd_replace_symbol = "[](bold purple)"
vimcmd_replace_one_symbol = "[](bold yellow)"

# Username style options
[username]
format = '\[[$user]($style)\]'

# Directory options
[directory]
format = "[$path]($style) [$read_only]($read_only_style)"
truncation_length = 8
truncation_symbol = "../"
truncate_to_repo = false
read_only = "󰌾"
style = 'bold blue'

# Git branch
[git_branch]
format = '\[[$symbol$branch](bold #769ff0)\]($style)'
symbol = " "

# Git commit
[git_commit]
# only_detached = false
format = '[\($hash$tag\)]($style)'

# Git status
[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'

# Git metrics
[git_metrics]
# disabled = false
format = "([+$added]($added_style))([-$deleted]($deleted_style))"
# only_nonzero_diffs = false

[c]
symbol = " "
format = '\[[$symbol($version(-$name))]($style)\]'
detect_extensions = ["c", "h", "cc", "cpp", "hh", "hpp"]

[lua]
symbol = " "
format = '\[[$symbol($version)]($style)\]'

[python]
symbol = " "
format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'

[nodejs]
symbol = " "
format = '\[[$symbol($version)]($style)\]'
